[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
collection_macros = "0.2.0"
dirs = "5.0.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
